# Generated by Django 4.2.13 on 2024-05-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudents',
            fields=[
                ('id_std', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_std', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hometown', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_students',
                'managed': True,
            },
        ),
    ]
