# Generated by Django 5.0.6 on 2024-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_std', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_std', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=20)),
                ('class_id', models.CharField(max_length=255)),
                ('hometown', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'tbl_student',
                'managed': False,
            },
        ),
    ]
