# Generated by Django 5.0.6 on 2024-05-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='tbl_students',
        ),
    ]
