# Generated by Django 4.2.13 on 2024-05-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
    ]
